### ISSUE TITLE
Multiple QC sessions can Collide in Browser Web Storage

### ISSUE THREAD

**Issue by jarmoza** [SIMEXP/dashQC_fmri#41]
If pipeline data processed by the same run of fmriprep_report or niak_report scripts gets run in the same browser by a different user, or if it gets split afterwards for separate QC sessions of QCing (@HanadS 's case), the current web storage code will assume the same QC session is being run.

This is because the unique identifier given to the processed data is a timestamp based on that script run. (See datasetID.js)

We need a way to 1) prevent such collisions and possibly 2) clear cache or add a new, separate instance of QC data in web storage based on the new session.

**Comment by surchs** [comment]
Ah, interesting. So the use case would be: Rater A and Rater B want to rate overlapping sets of individuals in the same browser session? So something like a hot-seat QC session? One option might be to ask users to 'log in' to dashQC with a user name that is then stored in the session an is prepended to the session ID. Changing the 'user name' could prompt to clear cache or keep the current ratings.
@HanadS would this address your problem?

**Comment by HanadS** [comment]
As Jon mentioned the output from the pipeline is split into different batches with different subjects. I then generate a dashboard seperately for each of these batches that gets stored in the same browser session. This part isn't really a problem for me because I want one combined json file for all the batchs. The only annoying part is figuring out which subject came from which batch. The main issue that I was having is when it comes loading the json file from another rater. I dont think its possible to load a combined json file into seperate dashboards. I guess a work around would be to ask the raters to clear their cache after finishing each batch. 

We have 3 raters using 3 different QC sessions. The idea of having log in for dashQC is cool but I think most of the time people will QC locally (Although I can see the benefit of having a shared QC session).

**Comment by surchs** [comment]
>  I then generate a dashboard seperately for each of these batches that gets stored in the same browser session. 

So you run `fmriprep_report`  / `niak_report` once on the preprocessed data, make copies of the dashQC folder that was created from the report script, and then manually remove subjects from the `listSubject.js` and `listRun.js` files? Is that correct? 

> This part isn't really a problem for me because I want one combined json file for all the batchs.

Ok, I get this. All the dashQC copies (with different subjects in them) would have the same run identifier because they were all generated in the same run by the report script. So as long as you are the only rater, this should not lead to conflicting ratings / overwritten data.

> The only annoying part is figuring out which subject came from which batch.

Right, this would indeed be difficult to figure out from the dashQC side since the changes to the copies of dashQC folders have been done by you manually and dashQC only knows they all have the same time stamp. I see two ways for you to figure out which session the individuals come from:
- load the `listSubject.js` files from the different copies and store the copy each subject is in
- when you go in to manually change the subjects in the `listSubjects.js` file, also change the time stamp in the `datasetID.js` file.

> The main issue that I was having is when it comes loading the json file from another rater. I dont think its possible to load a combined json file into seperate dashboards.

Ok, so if I understand this right, some other rater has rated more than one of the subsets / copies of your data, leading to a json file that combines ratings from more than subset. If you try to load this combined json file with ratings into the dashboard of a single subset, you get some error message because the dashboard only knows about some of the individuals in the json. Is that correct?

I see three solutions for this:
1. As you said, ask raters to clear their cache for each subset of data / ratings
2. Have dashQC ignore ratings for subjects it doesn't know about (no raw data / not in `listSubjects.js`) so at least you can load combined files and only see the ratings for guys in your dashboard
3. Edit the report script with an argument that splits the sample into subsamples of a certain size. For example, if you have a preprocessed dataset of 100 subjects and you specify a `n_split = 30` you'd get 3 subsamples of 30 subjects each and one of 10 subjects. Since that would happen during generation of the dashQC folder, we could give each subsample a unique timestamp / dataset ID and avoid all of this

**Comment by jarmoza** [comment]
@HanadS Could you say again at what point the splitting into multiple batches occurs? Is it before you run the Python script or afterward?

**Comment by HanadS** [comment]
> So you run `fmriprep_report` / `niak_report` once on the preprocessed data, make copies of the dashQC folder that was created from the report script, and then manually remove subjects from the `listSubject.js` and `listRun.js` files? Is that correct?

I split into multiple batches before running the python script so I do not touch those js files. @jarmoza I did this to initially make running the pipeline more manageable because NIAK will often crash.  But I think it's causing more problems than its solving so I may stop doing this. 

>     * load the `listSubject.js` files from the different copies and store the copy each subject is in
> 
>     * when you go in to manually change the subjects in the `listSubjects.js` file, also change the time stamp in the `datasetID.js` file.

 Okay, I will try this. Thanks

> Ok, so if I understand this right, some other rater has rated more than one of the subsets / copies of your data, leading to a json file that combines ratings from more than subset. If you try to load this combined json file with ratings into the dashboard of a single subset, you get some error message because the dashboard only knows about some of the individuals in the json. Is that correct?

> I see three solutions for this:

>     1. As you said, ask raters to clear their cache for each subset of data / ratings 
>     2. Have dashQC ignore ratings for subjects it doesn't know about (no raw data / not in `listSubjects.js`) so at least you can load combined files and only see the ratings for guys in your dashboard
>     3. Edit the report script with an argument that splits the sample into subsamples of a certain size. For example, if you have a preprocessed dataset of 100 subjects and you specify a `n_split = 30` you'd get 3 subsamples of 30 subjects each and one of 10 subjects. Since that would happen during generation of the dashQC folder, we could give each subsample a unique timestamp / dataset ID and avoid all of this. 

I like option 3. When we are QCing datasets with 10,000+ scans, I'm not sure this can be stored in a single browser session so having an option where we can split the data would be very nice.

**Comment by HanadS** [comment]
Closing this issue because it is similar to issue nine. The option to combine multiple JSON files for the same dataset would be useful but not needed (speaking for myself) at the moment.
