### ISSUE TITLE
 'Save QC'  gives a json file with subjects generated in other dashboards. 

### ISSUE THREAD

**Issue by HanadS** [SIMEXP/dashQC_fmri#9]
Expected to have output from subjects in current dashboard.

Given output from all subjects in all dashboards generated.

**Comment by jarmoza** [comment]
Since NIAK (if not fmriprep) does not output a unique session ID for the data set in its JSON, the dashQC script that converts between these output formats (NIAK, fmriprep) and the dashQC folder/file format will also create a JSON file that lists a unique ID and date so there is no conflict between old web storage data and the underlying fmri image/data files.

**Comment by jarmoza** [comment]
@HanadS This issue should be resolved. Can you test?
